services:
  client:
    build:
      context: ./Client
      dockerfile: ./Dockerfile
    container_name: expense-tracker-frontend
    ports:
      - '5173:5173'
    env_file: 
      - path: ./Client/.env
    depends_on:
      - server

  server:
    build:
      context: ./Server
      dockerfile: ./Dockerfile
    container_name: expense-tracker-backend
    ports:
      - '3000:3000'
    env_file: 
      - path: ./Server/.env
